export { default as TopBar } from "./TopBar/TopBar";
export { default as Login } from "./Login/Login";
export { default as Register } from "./Register/Register";
export { default as ForgotPassword } from "./ForgotPassword/ForgotPassword";
export { default as ResetPassword } from "./ResetPassword/ResetPassword";
export { default as Theme } from "./Theme/Theme";
export { default as Language } from "./Language/Language";
export { default as HeroSection} from "./HeroSection/HeroSection";
export { default as Functionalities} from "./Functionalities/Functionalities";
export { default as FAQ } from "./FAQ/FAQ";
export { default as FAQCard } from "./FAQCard/FAQCard";
export { default as Footer } from "./Footer/Footer";
export { default as GoTop } from "./GoTop/GoTop";
export { default as Unauthorized } from "./Unauthorized/Unauthorized";
